baseurl = "/"
languageCode = "en-us"
title = "A minimal Hugo website"
theme = "hugo-titi"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "â†©"

[permalinks]
    post = "/post/:year-:month-:day/:slug/"
    note = "/note/:year-:month-:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Methodology"
    url = "/methodology/"
    weight = 3
[[menu.main]]
    name = "Data"
    url = "/data/"
    weight = 4
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 5
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 6
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "A website built through Hugo, blogdown and Titi"
    footer = "&copy; [Datasketch](https://datasketch.co) 2017 -- 2018 | [Github](https://github.com/datasketch) | [Twitter](https://twitter.com/xiedatasketch)"
