baseURL = "/"
title = "Titi"
theme = "hugo-titi"
themesDir = "../.."
disqusShortname = "datasketch"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[menu]
  [[menu.burger]]
    name = "Inicio"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Metodología"
    url = "/metodologia"
    weight = 1

[params]
  # SEO general site description
  description = "Site SEO description"

  [params.nav]
    bg = "#eee"
    color = "black"
    logo = "images/ds-logo.svg"
    logoWidth = "150px"
    # Optional, true by default
    # fixed = true

  [[params.social]]
    icon = "twitter"
    url = "https://twitter.com/datasketch"
  [[params.social]]
    icon = "facebook"
    url = "https://www.facebook.com/datasketch/"
  [[params.social]]
    icon = "instagram"
    url = "https://www.instagram.com/datasketch/"

  [params.footer]
    text = "Todo el material en esta página es [CC-BY-SA](https://creativecommons.org/licenses/by-sa/4.0/). Si reusas o adaptas recursos de esta página, por favor vincula y referencia nuestro artículo o sitio web."
    bg = "black"
    color = "white"
